services:

  backend:
    build: .
    container_name: helpdesk-backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: helpdesk
      DATABASE_USER: admin
      DATABASE_PASSWORD: password123
    depends_on:
      - database
    restart: always


  database:
    image: postgres:16
    container_name: helpdesk-db
    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always


volumes:
  postgres_data:
